In [1]:
import numpy as np

In [2]:
# first three element
arr= np.array([3, 6, 9, 12, 15])
arr[0:3:1]

array([3, 6, 9])

In [3]:
# last two element
arr[-1:-3:-1]

array([15, 12])

In [4]:
# element from index 1 to 4
arr[1:5]

array([ 6,  9, 12, 15])

In [5]:
# filtering the data with boolean filtering
arr[arr>10]

array([12, 15])

In [6]:
# Basic Math
arr+5
arr*5
arr/5
arr**2

array([  9,  36,  81, 144, 225])

In [7]:
# Aggregate Functions
# mean 
arr.mean()

np.float64(9.0)

In [8]:
# sum 
arr.sum()

np.int64(45)

In [9]:
# min 
arr.min()

np.int64(3)

In [10]:
# max
arr.max()

np.int64(15)

In [11]:
#  standard deviation (std)
arr_2 = np.array([2, 2, 2, 2, 2, 2])
arr_2.std()

np.float64(0.0)

In [12]:
# reshape
a = np.array([1,2,3,4,5,6])
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# matrix operation
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

A + B # addition
A - B # substraction
A @ B # multiplication
np.dot(A,B)  # multiplication
np.transpose(A) # transpose

array([[1, 3],
       [2, 4]])

In [14]:
# Broadcasting
array = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([10,20,30])

array + v

array([[11, 22, 33],
       [14, 25, 36]])

In [15]:
# Axis Practice
arr_3 = np.array([[2, 4, 6], [1, 3, 5]])
np.sum(arr_3, axis=0) # axis 0 indicate sum on all collum
np.sum(arr_3, axis=1) # axis 1 indicate sum on all row

array([12,  9])