In [1]:
import numpy as np

In [2]:
arr = np.array([2,3,4])
arr + 10

array([12, 13, 14])

In [3]:
arr = np.array([2,3,4])
arr * 10

array([20, 30, 40])

In [5]:
arr = np.array([2,3,4])
arr ** 2

array([ 4,  9, 16])