In [1]:
import numpy as np

In [3]:
narray = np.array([10, 20, 30, 40, 50])
narray

array([10, 20, 30, 40, 50])

In [ ]:
# accesing array with index
narray[2]

np.int64(30)

In [ ]:
# accesing last element of array.
narray[-1]

np.int64(50)

In [13]:
# slice the array
# it start from the index which is indicated and stop before the 1 index. [start:stop:step]
narray[-1: -4: -1]

array([50, 40, 30])

In [ ]:
# filter to find the numbers 
narray[narray <20]

array([10])