In [4]:
import numpy as np

In [5]:
# making array
np.array([1, 6 ,6])

array([1, 6, 6])

In [6]:
# checking dimension with ndim
narray= np.array([1,2,3])
narray.ndim

narray_2= np.array([[[]]])
narray_2.ndim

3

In [7]:
# range
range = np.arange(1, 10, 2) # ==> (start, stop, jump)
range

array([1, 3, 5, 7, 9])

In [8]:
# logspace: telling that (starting powers, ending powers, points)
logspace = np.logspace(1, 3, 3)
# logspace
logspace_2= np.logspace(2, 4, 2)
logspace_2

array([  100., 10000.])

In [37]:
# making matrix with zeros
zero= np.zeros([3, 2])
zero

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
# ones
c = np.ones((3, 2))
c

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
# random numbers
random = np.random.rand(3)
random

array([0.37747922, 0.03132812, 0.38420806])

In [11]:
# array size::-->> shape tells the size
narray = np.array([1,3,5])
narray.shape

(3,)