In [1]:
import numpy as np

In [7]:
# creating 2d array
arr1 = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])
arr1.shape

(2, 4)

In [8]:
# creating 3d array
arr2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr2.shape

(2, 2, 2)

In [20]:
# reshaping aray
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
re_arr= arr.reshape(3,4)
re_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# transpose the array
re_arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
# make one dimensional array
a = np.array([[5, 6], [7, 8]])
res = a.flatten()
res

array([5, 6, 7, 8])