In [35]:
import numpy as np


In [36]:
# array creating
arr = np.array([12, 34,56,90])

In [37]:
# array slicing
arr[1:3]

array([34, 56])

In [38]:
# last two elements
arr[-1: -5: -1]

array([90, 56, 34, 12])

In [39]:
# filtering the data with boolean filtering
arr[arr<50]

array([12, 34])

In [40]:
# basic math
arr+5
arr-1
arr*2
arr/2

array([ 6., 17., 28., 45.])

In [41]:
# aggregate fn
arr.mean()
arr.max()
arr.min()
arr.std()
# arr

np.float64(28.809720581775867)

In [ ]:
# reshaping the array
# a = np.array([1,2,3,4,5,6])
# a
# a.reshape([2, 3])

In [ ]:
# array multiplication, addition, substraction
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

mul = np.dot(A, B)
mul

array([[19, 22],
       [43, 50]])

In [50]:
# Broadcasting
b_array = np.array([1, 2])
A + b_array

array([[2, 4],
       [4, 6]])